export const ERROR_CODES = {
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  MICROSOFT_TOKEN_INVALID: "MICROSOFT_TOKEN_INVALID",
  TENANT_NOT_ALLOWED: "TENANT_NOT_ALLOWED",
  USER_PENDING_ROLE: "USER_PENDING_ROLE",
  USER_DISABLED: "USER_DISABLED",
  FORBIDDEN: "FORBIDDEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_ROLE: "INVALID_ROLE",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  LAST_ADMIN_PROTECTION: "LAST_ADMIN_PROTECTION",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Maps each stable error code to the HTTP status it must be surfaced as. */
export const ERROR_STATUS: Record<ErrorCode, number> = {
  AUTH_TOKEN_MISSING: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_TOKEN_EXPIRED: 401,
  MICROSOFT_TOKEN_INVALID: 401,
  TENANT_NOT_ALLOWED: 403,
  USER_PENDING_ROLE: 403,
  USER_DISABLED: 403,
  FORBIDDEN: 403,
  USER_NOT_FOUND: 404,
  INVALID_ROLE: 400,
  INVALID_STATUS_TRANSITION: 400,
  LAST_ADMIN_PROTECTION: 409,
  VALIDATION_ERROR: 400,
  RATE_LIMIT_EXCEEDED: 429,
  DATABASE_ERROR: 500,
  INTERNAL_ERROR: 500,
  EXTERNAL_SERVICE_ERROR: 502,
};

export class AppError extends Error {
  code: ErrorCode;
  fields?: Record<string, string>;

  constructor(code: ErrorCode, message: string, fields?: Record<string, string>) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.fields = fields;
  }
}
